import Foundation

/// Result of note generation — structured meeting notes organized by topic.
struct GeneratedNotes {
    let title: String?
    let overview: String
    let topics: [DiscussionTopic]
    let decisions: [String]
    let actionItems: [ActionItem]
    /// True if notes were generated by AI, false if heuristic fallback.
    let isAIGenerated: Bool
}

/// Generates structured meeting notes from a transcript.
/// Priority: (1) Apple on-device AI (iOS 26+), (2) Claude API (if key configured),
/// (3) basic keyword extraction.
final class AISummaryService: ObservableObject, @unchecked Sendable {
    @Published var isSummarizing = false

    /// Whether an Anthropic API key is saved in Keychain.
    var hasAPIKey: Bool {
        guard let key = KeychainHelper.read(key: "anthropic_api_key") else { return false }
        return !key.isEmpty
    }

    /// Generate structured meeting notes from a transcript.
    func generateNotes(from transcript: String) async throws -> GeneratedNotes {
        await MainActor.run { isSummarizing = true }
        defer { Task { @MainActor in isSummarizing = false } }

        // 1. On-device AI (iOS 26+) — free, private, no API key needed
        if #available(iOS 26, *) {
            do {
                print("[AISummary] Trying on-device Foundation Models...")
                let notes = try await OnDeviceAIService.summarize(transcript: transcript)
                let topics = notes.topics.map {
                    DiscussionTopic(heading: $0.heading, bulletPoints: $0.bulletPoints)
                }
                let actionItems = notes.actionItems.map { ActionItem(text: $0) }
                print("[AISummary] On-device SUCCESS: \(notes.overview.count) char overview, \(topics.count) topics, \(notes.decisions.count) decisions, \(actionItems.count) actions")
                return GeneratedNotes(
                    title: notes.title,
                    overview: notes.overview,
                    topics: topics,
                    decisions: notes.decisions,
                    actionItems: actionItems,
                    isAIGenerated: true
                )
            } catch {
                print("[AISummary] On-device AI failed: \(error), trying next option...")
            }
        }

        // 2. Claude API (developer/power-user option)
        if hasAPIKey {
            print("[AISummary] Trying Claude API...")
            do {
                let notes = try await ClaudeService.summarize(transcript: transcript)
                let topics = notes.topics.map {
                    DiscussionTopic(heading: $0.heading, bulletPoints: $0.bulletPoints)
                }
                let actionItems = notes.actionItems.map { ActionItem(text: $0) }
                print("[AISummary] Claude SUCCESS: \(notes.overview.count) char overview, \(topics.count) topics, \(notes.decisions.count) decisions, \(actionItems.count) actions")
                return GeneratedNotes(
                    title: notes.title,
                    overview: notes.overview,
                    topics: topics,
                    decisions: notes.decisions,
                    actionItems: actionItems,
                    isAIGenerated: true
                )
            } catch {
                print("[AISummary] Claude API FAILED: \(error)")
            }
        }

        // 3. Heuristic fallback: keyword extraction only
        let result = generateHeuristicNotes(from: transcript)
        print("[AISummary] Heuristic: \(result.actionItems.count) actions, \(result.decisions.count) decisions")
        return result
    }

    // MARK: - Heuristic fallback

    private func generateHeuristicNotes(from transcript: String) -> GeneratedNotes {
        let sentences = splitSentences(transcript)
        let wordCount = transcript.split(separator: " ").count

        let overview = "Recording transcribed (\(wordCount) words). AI-powered notes will be available on devices with Apple Intelligence."

        let decisions = extractDecisions(from: sentences)
        let actionItems = extractActionItems(from: sentences)

        return GeneratedNotes(
            title: nil,
            overview: overview,
            topics: [],
            decisions: decisions,
            actionItems: actionItems,
            isAIGenerated: false
        )
    }

    // MARK: - Sentence splitting

    private func splitSentences(_ transcript: String) -> [String] {
        let normalized = transcript
            .replacingOccurrences(of: "\n\n", with: ". ")
            .replacingOccurrences(of: "\n", with: " ")
        return normalized
            .components(separatedBy: ". ")
            .flatMap { $0.components(separatedBy: "? ") }
            .flatMap { $0.components(separatedBy: "! ") }
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { $0.count > 3 }
    }

    // MARK: - Decision extraction

    private func extractDecisions(from sentences: [String]) -> [String] {
        let decisionWords = [
            "decided", "agreed", "approved", "confirmed", "settled",
            "conclusion", "resolved", "committed", "finalized", "chose"
        ]
        var decisions: [String] = []

        for sentence in sentences {
            let normalized = sentence.lowercased()
            if decisionWords.contains(where: { normalized.contains($0) }) {
                decisions.append(ensurePeriod(sentence))
                if decisions.count >= 5 { break }
            }
        }
        return decisions
    }

    // MARK: - Action item extraction

    private func extractActionItems(from sentences: [String]) -> [ActionItem] {
        let actionPatterns = [
            "need to", "should", "will do", "action item", "follow up",
            "todo", "to do", "must", "let's", "let us", "we'll",
            "going to", "have to", "make sure", "don't forget",
            "remember to", "assign", "responsible for"
        ]
        var items: [ActionItem] = []
        var seen = Set<String>()

        for sentence in sentences {
            let trimmed = sentence.trimmingCharacters(in: .whitespacesAndNewlines)
            let normalized = trimmed.lowercased()
            guard !seen.contains(normalized) else { continue }

            if actionPatterns.contains(where: { normalized.contains($0) }) {
                seen.insert(normalized)
                items.append(ActionItem(text: ensurePeriod(trimmed)))
            }
        }
        return items
    }

    // MARK: - Helpers

    private func ensurePeriod(_ s: String) -> String {
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.hasSuffix(".") || trimmed.hasSuffix("?") || trimmed.hasSuffix("!") {
            return trimmed
        }
        return trimmed + "."
    }
}
